name: Playwright Regression Automation

on:
  schedule:
    # 9:00 AM IST
    - cron: '30 3 * * *'

    # 6:00 PM IST
    - cron: '30 12 * * *'

  workflow_dispatch:

jobs:
  regression-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Regression Test
        run: npx playwright test tests/regression.spec.js

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/